id: I10411CFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:29:48+00:00'
last_modified: '2022-06-09T06:34:07.079730+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23688
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དབང་མོའི་སྒྲུབ་ཐབས་བསྙེན་སྒྲུབ་སྦྱིན་སྲེག་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    F404:
      image_group_id: I2472
      title: ''
      total_pages: 686
      order: 1
      base_file: F404.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
