id: opecha:P007849
initial_creation_type: ocr
source_metadata:
  id: bdr:W23688
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དབང་མོའི་སྒྲུབ་ཐབས་བསྙེན་སྒྲུབ་སྦྱིན་སྲེག་སོགས
  volume: ''
  author: ''
