id: P007849
initial_creation_type: ocr
source_metadata:
  id: bdr:W23688
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དབང་མོའི་སྒྲུབ་ཐབས་བསྙེན་སྒྲུབ་སྦྱིན་སྲེག་སོགས
  author: ''
  volumes:
    fead0c67a729415faee084af922546b0:
      image_group_id: I2472
      title: ''
      volume_number: 1
      total_pages: 686
ebook_metadata:
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དབང་མོའི་སྒྲུབ་ཐབས་བསྙེན་སྒྲུབ་སྦྱིན་སྲེག་སོགས
  author: ''
  sku: P007849
  cover: cover.jpg
  layers:
  - pagination
