id: P007849
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:44:52.459219
source_metadata:
  id: bdr:W23688
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དབང་མོའི་སྒྲུབ་ཐབས་བསྙེན་སྒྲུབ་སྦྱིན་སྲེག་སོགས
  author: ''
  volumes:
    1a9234c44a4b481ea7de545089140a00:
      image_group_id: I2472
      title: ''
      volume_number: 1
      total_pages: 686
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
